language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools
    - platform-tools
    - build-tools-26.0.1
    - android-26

jdk:
  - oraclejdk8 # to support lambda expressions